Adding admin users to Data 8x hub for Issue: #2813
berkeley-dsep-infra/hubs pull request #2822
Opened 2021-09-30 23:40 UTC by balajialg

2021-10-01 13:57 UTC, yuvipanda requested changes

2021-10-01 13:57 UTC, yuvipanda commented on deployments/data8x/config/common.yaml
> +          - ericvd
Their EdX IDs needed to be added here - they look like the random strings you see above. You can find yours by:

1. Enrolling in the class
2. Launching into the lab
3. Finding the user id from control panel

2021-10-04 22:02 UTC, yuvipanda commented
@balajialg can you split this into two PRs? We can't actually merge this one because  the EdX ids are not here yet, and so we can't get the packages installed.

2021-10-04 22:04 UTC, yuvipanda commented
You can use the `git cherry-pick` command to get the latest commit alone onto another branch, and use it for a new PR?

2021-10-04 22:15 UTC, balajialg commented
@yuvipanda I updated Sean Morris's EdX id as part of this PR! You can check that as part of the commit I made just now. Let me know if you still want me to create a new PR!

Sorry about both the commits! I didn't know how to cherry-pick the last commit and create a different pull request. Thanks for your inputs.

2021-10-04 22:19 UTC, merged