[Sp24 DS100] 1. Admin access (thru bcourses `Admins` user group) 2. Grant DS100 Content Team 4G RAM.
berkeley-dsep-infra/hubs pull request #5375
Opened 2024-01-13 05:59 UTC by CharlieJCJ

Start of semester datahub access request. 

Thanks,
Charlie

2024-01-15 02:06 UTC, balajialg commented
@CharlieJCJ thanks for creating this PR! Can you please link the github issue https://github.com/berkeley-dsep-infra/datahub/issues/5376 as a comment?

2024-01-15 07:45 UTC, CharlieJCJ commented
For sure! [Issue](https://github.com/berkeley-dsep-infra/datahub/issues/5376) linked.

2024-01-15 07:50 UTC, CharlieJCJ commented
Yeah, just a note. I added a commit to revert back to prev fa23 package version and will open a separate PR, issue for package updates.

2024-01-16 19:25 UTC, CharlieJCJ commented
@balajialg waiting for merge approval, thanks!

2024-01-16 19:51 UTC, balajialg commented
@CharlieJCJ Sounds good. Seems like I didn't communicate the change properly. Can you please link the github issue https://github.com/berkeley-dsep-infra/datahub/issues/5376 as a comment in the PR for our internal tracking purposes? I will merge the PR to staging ASAP. Having said that, @shaneknapp intends to merge all the changes to prod after 5 PM today. So, these changes will only go live tonight. Hope that works for you and your team @CharlieJCJ

2024-01-16 19:53 UTC, shaneknapp requested changes

2024-01-16 19:53 UTC, shaneknapp commented on deployments/data100/image/environment.yml
> +  - ydata-profiling==4.6.4
could you revert any changes to this file please?  thanks!

2024-01-16 20:09 UTC, CharlieJCJ commented on deployments/data100/image/environment.yml
> +  - ydata-profiling==4.6.4
Done, thanks for pointing out!

2024-01-16 20:11 UTC, CharlieJCJ commented
Fixed all. Thanks!

2024-01-16 20:18 UTC, ryanlovett approved these changes
@balajialg Looks good to me.

2024-01-16 20:23 UTC, merged