[DH-274] Changing shared-readwrite from /opt to /home/jovyan in Stat 20 hub for infra admins!
berkeley-dsep-infra/hubs pull request #5686
Opened 2024-04-19 00:02 UTC by balajialg

Re: https://github.com/berkeley-dsep-infra/datahub-usage-analysis/pull/17
https://jira-secure.berkeley.edu/browse/DH-274

2024-04-19 01:32 UTC, ryanlovett requested changes
First, sorry for not mentioning this earlier in the other thread where I referenced stat159 and /opt...

Second, I think we shouldn't alter the existing volume mounts -- we should add a new one just for this project. The existing ones are for course data. If you were to merge as is, and drop the data into `_shared`, the students would be able to see the data.

- This should be a new volume mount scoped under `group_profiles.course::1524699::group::all-admins:'
- It shouldn't use the directory name `shared-readwrite` since 1) the volume will be mounted read-only and 2) `shared-readwrite` and `shared` are part of a convention used in the hubs across all courses. That name should be set aside for course data. Since this change is for datahub admins, we can mount it as `/home/jovyan/shared-524699-admins` or some such.
- `_shared` should be `_shared-524699-admins` or some such since `_shared` is again reserved for course data.

2024-04-19 17:35 UTC, balajialg commented
Thanks @ryanlovett for the clarification. I was aware of the protocol for shared/shared-read-write directories since I had handled [such requests in the past](https://github.com/berkeley-dsep-infra/datahub/pull/5644/commits/31f2199e52b57bc0c9a6f93293d5e18cbbdafabd). However, I got confused with the admin stanza listed below. For a moment, I thought that this stanza needs to get fixed for admins instead of adding a new stanza linking bcourses id (as we do for user requests). My bad! 

```
    admin:
      extraVolumeMounts:
        - name: home
          mountPath: /opt/shared-readwrite
          subPath: _shared
```

2024-04-22 20:53 UTC, balajialg commented
@ryanlovett @shaneknapp Let me know if you are okay with merging the changes to staging?

2024-04-22 21:10 UTC, shaneknapp commented on deployments/stat20/config/common.yaml
> +          subPath: _shared
add a new line after `_shared` please

2024-04-22 21:36 UTC, balajialg commented on deployments/stat20/config/common.yaml
> +          subPath: _shared
Done

2024-04-22 21:48 UTC, shaneknapp commented
looks good to me...

On Mon, Apr 22, 2024 at 2:36 PM Balaji Alwar ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In deployments/stat20/config/common.yaml
> <https://github.com/berkeley-dsep-infra/datahub/pull/5686#discussion_r1575383933>
> :
>
> >      admin:
>        extraVolumeMounts:
>          - name: home
>            mountPath: /opt/shared-readwrite
> -          subPath: _shared
> +          subPath: _shared
>
> Done
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/berkeley-dsep-infra/datahub/pull/5686#discussion_r1575383933>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMIHLAIQPBIG4XIXMD3FKTY6V7GJAVCNFSM6AAAAABGOGT7JOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMJVHA2DINBUHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-23 18:00 UTC, merged