[DH-276] update cluster switchover doc
berkeley-dsep-infra/hubs pull request #5750
Opened 2024-05-21 20:55 UTC by shaneknapp

2024-05-28 17:31 UTC, shaneknapp commented on docs/admins/howto/clusterswitch.md
> +## Switch DNS to the new cluster's endpoint IP and point our deployment at it.
@felder i could definitely use your eyes on this section...  :)

2024-06-06 00:42 UTC, shaneknapp commented
@ryanlovett @felder it'd be great if you could put your peepers on these changes for any feedback.

thanks!

2024-06-07 16:56 UTC, ryanlovett commented
@shaneknapp Seems clear to me! I didn't participate in most the upgrade so I don't know if anything is missing. The cert-manager section seems accurate though, from what I recall.

Either in this PR or another, it might be good to document in a sentence or two why it can be necessary to deploy a new cluster.

2024-06-14 21:05 UTC, felder requested changes, later dismissed
I commented and suggested edits for the specific section you asked me about.  I think everything else looks reasonable, but it's hard to know for sure.  I guess we can cross  that bridge the next time we do a cluster rotation and refer to this doc.

2024-06-14 21:05 UTC, felder commented on docs/admins/howto/clusterswitch.md
> +## Switch DNS to the new cluster's endpoint IP and point our deployment at it.
Yeah I think this is not quite right.

I don't think the endpoint is relevant.  So basically what infoblox points to is the loadbalancer that's created as part of the ingress-controller service in the support chart.  So roughly, I believe the series of steps for this is to:

1.  Allocate a new static ip via the GCP console.
2. Configure the wildcard and empty (datahub.berkeley.edu) records in infoblox to point to the new ip.
3. Configure the loadBalancerIP for ingress-nginx in support/values.yaml to use the new ip.
4. Redeploy the support chart to pick up the change.
5. Confirm via the GCP console that the IP that was defined in step 1 is now bound to a forwarding rule.  You can further confirm by listing the services in the support chart and making sure the ingress-controller is using the newly defined IP.

2024-06-17 20:19 UTC, shaneknapp commented
@felder let me know if the changes from [79bcd14f1f76242984e362c92bffabb9ebb66261](https://github.com/berkeley-dsep-infra/datahub/pull/5750/commits/79bcd14f1f76242984e362c92bffabb9ebb66261) look good!

2024-06-17 20:26 UTC, shaneknapp commented
> @shaneknapp Seems clear to me! I didn't participate in most the upgrade so I don't know if anything is missing. The cert-manager section seems accurate though, from what I recall.
> 
> Either in this PR or another, it might be good to document in a sentence or two why it can be necessary to deploy a new cluster.

https://github.com/berkeley-dsep-infra/datahub/pull/5750/commits/0558bb96f43f4fe25308d2af4f48b102c4735046

2024-06-17 21:21 UTC, merged